/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;

/**
 *
 * @author jared
 */
public class login extends javax.swing.JFrame {
   private ArrayList<usuario> listaUsuarios;
  
    /**
     * Creates new form login
     */
    public login(ArrayList<usuario> listaUsuarios) {
         this.listaUsuarios = listaUsuarios;
        initComponents();
        
    jPanel1.setBorder(null);           // Quita el borde
    jPanel1.setOpaque(false);   
     
        
    txtusuario.setBorder(BorderFactory.createEmptyBorder(12, 15, 12, 15)); // Padding interno
txtusuario.setBackground(new Color(20, 30, 50, 220)); // Fondo negro-azulado con transparencia
txtusuario.setForeground(new Color(173, 216, 230)); // Azul claro (como el cielo)
txtusuario.setCaretColor(new Color(186, 85, 211)); // Morado medio (orchid)
txtusuario.setFont(txtusuario.getFont().deriveFont(14f)); // Letra un poco más grande

// Campo de contraseña
txtcontraseña.setBorder(BorderFactory.createEmptyBorder(12, 15, 12, 15));
txtcontraseña.setBackground(new Color(20, 30, 50, 220)); // Igual que usuario para consistencia
txtcontraseña.setForeground(new Color(173, 216, 230)); // Azul cielo
txtcontraseña.setCaretColor(new Color(186, 85, 211)); // Morado orchid
txtcontraseña.setFont(txtcontraseña.getFont().deriveFont(14f));
    
 
    
    
    
        
        System.out.println("Usuarios en login:");
    for (usuario u : listaUsuarios) {
        System.out.println("Correo: " + u.getCorreo() + ", Contraseña: " + u.getContraseña());
    }
          
    agregarFondo(jPanel1, new fondodegradado());
    agregarFondo(jPanel2, new fondodegradadopanel2());
     this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
     this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                   Object[] opciones = {"Sí", "No"};
                 int confirm = JOptionPane.showOptionDialog(null, 
                        "¿Deseas salir?", 
                        "Confirmar salida", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, 
                        null, 
                        opciones, 
                        opciones[1]);

                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
}


private void agregarFondo(JPanel panel, JPanel fondo) {
    fondo.setBounds(0, 0, panel.getWidth(), panel.getHeight());
    panel.add(fondo);
    panel.setComponentZOrder(fondo, panel.getComponentCount() - 1);

    
    panel.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            fondo.setBounds(0, 0, panel.getWidth(), panel.getHeight());
            fondo.repaint();
        }
    });
    

getContentPane().setBackground(new Color(48, 25, 52)); // Un morado oscuro elegante

  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btningresar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        chkmostrarcontra = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        lblErrorCorreo = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();
        lblErrorContrasena = new javax.swing.JLabel();
        lblerrorcontraycorreo = new javax.swing.JLabel();
        botonBonito1 = new BotonBonito();
        botonBonito2 = new BotonBonito();

        btningresar.setBackground(new java.awt.Color(51, 0, 204));
        btningresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btningresar.setForeground(new java.awt.Color(255, 255, 255));
        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(153, 255, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TuMotoRun");
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TuMotoRun");

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("BIENVENIDO A LA MEJOR TIENDA DE MOTOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Ingresar la contraseña:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Ingresar correo:");

        chkmostrarcontra.setForeground(new java.awt.Color(255, 255, 255));
        chkmostrarcontra.setText("Mostrar contraseña");
        chkmostrarcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmostrarcontraActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\jared\\Downloads\\iconologin (2).jpg")); // NOI18N

        lblErrorCorreo.setForeground(new java.awt.Color(255, 0, 51));

        lblErrorContrasena.setForeground(new java.awt.Color(255, 0, 51));

        lblerrorcontraycorreo.setForeground(new java.awt.Color(255, 51, 51));

        botonBonito1.setIcon(null);
        botonBonito1.setText("Ingresar");
        botonBonito1.setColorFin(new java.awt.Color(255, 51, 255));
        botonBonito1.setColorFinHover(new java.awt.Color(204, 255, 255));
        botonBonito1.setColorInicio(new java.awt.Color(102, 153, 255));
        botonBonito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBonito1ActionPerformed(evt);
            }
        });

        botonBonito2.setIcon(null);
        botonBonito2.setText("Limpiar");
        botonBonito2.setColorFin(new java.awt.Color(255, 51, 51));
        botonBonito2.setColorFinHover(new java.awt.Color(255, 204, 204));
        botonBonito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBonito2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel6))
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkmostrarcontra)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblerrorcontraycorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(botonBonito1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBonito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblErrorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblerrorcontraycorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(chkmostrarcontra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBonito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(botonBonito2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkmostrarcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmostrarcontraActionPerformed
    
 if (chkmostrarcontra.isSelected()) {
        txtcontraseña.setEchoChar((char) 0);
    } else {
        txtcontraseña.setEchoChar('•'); 
    }
    }//GEN-LAST:event_chkmostrarcontraActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
         txtusuario.setText("");  
    txtcontraseña.setText(""); 
    lblErrorCorreo.setText(""); 
    lblErrorContrasena.setText("");
    
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void botonBonito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBonito1ActionPerformed
        String correo = txtusuario.getText();
    String contrasena = new String(txtcontraseña.getPassword());
    boolean correoValido = validacion.validarCorreo(correo);

    lblErrorCorreo.setText("");
    lblErrorContrasena.setText("");
    lblerrorcontraycorreo.setText("");

    if (!correoValido) {
        lblErrorCorreo.setText("Correo inválido.");
        return;
    }

    // Caso especial: administrador fijo
    if (correo.equals("jared@gmail.com") && contrasena.equals("jared123")) {
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso como administrador");
        bienvenida ventana = new bienvenida("Jared", "Administrador");
        ventana.setVisible(true);
        this.dispose();
        return;
    }

    // Verificar en la BD
    String[] datos = verificarCredencialesEnBD(correo, contrasena);

    if (datos != null) {
        String nombre = datos[0];
        String rol = datos[1];
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso como " + rol);
        bienvenida ventana = new bienvenida(nombre, rol);
        ventana.setVisible(true);
        this.dispose();
    } else {
        lblerrorcontraycorreo.setText("Correo o contraseña incorrectos");
    }
    }//GEN-LAST:event_botonBonito1ActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        String correo = txtusuario.getText();
    String contrasena = new String(txtcontraseña.getPassword());
    boolean correoValido = validacion.validarCorreo(correo);

    lblErrorCorreo.setText("");
    lblErrorContrasena.setText("");
    lblerrorcontraycorreo.setText("");

    if (!correoValido) {
        lblErrorCorreo.setText("Correo inválido.");
        return;
    }

    // Caso especial: administrador fijo
    if (correo.equals("jared@gmail.com") && contrasena.equals("jared123")) {
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso como administrador");
        bienvenida ventana = new bienvenida("Jared", "Administrador");
        ventana.setVisible(true);
        this.dispose();
        return;
    }

    // Verificar en la BD
    String[] datos = verificarCredencialesEnBD(correo, contrasena);

    if (datos != null) {
        String nombre = datos[0];
        String rol = datos[1];
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso como " + rol);
        bienvenida ventana = new bienvenida(nombre, rol);
        ventana.setVisible(true);
        this.dispose();
    } else {
        lblerrorcontraycorreo.setText("Correo o contraseña incorrectos");
    }
        }

        // Método para verificar las credenciales en la base de datos
        private String[] verificarCredencialesEnBD(String correo, String contrasena) {
          conexion.conexionMysql con = new conexion.conexionMysql();
    Connection conectar = con.conexion();

    if (conectar == null) {
        JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return null;
    }

    try {
        String sql = "SELECT u.nombre, r.nombre_rol " +
                     "FROM usuarios u " +
                     "JOIN roles r ON u.id_rol = r.id_rol " +
                     "WHERE u.correo = ? AND u.contrasena = ?";
        PreparedStatement ps = conectar.prepareStatement(sql);
        ps.setString(1, correo);
        ps.setString(2, contrasena);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String[] datos = new String[2];
            datos[0] = rs.getString("nombre");
            datos[1] = rs.getString("nombre_rol");
            rs.close();
            ps.close();
            conectar.close();
            return datos;
        }

        rs.close();
        ps.close();
        conectar.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al verificar credenciales: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    return null; // si no encontró nada
    }//GEN-LAST:event_btningresarActionPerformed

    private void botonBonito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBonito2ActionPerformed
           txtusuario.setText("");  
    txtcontraseña.setText(""); 
    lblErrorCorreo.setText(""); 
    lblErrorContrasena.setText("");
    }//GEN-LAST:event_botonBonito2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new login(new ArrayList<usuario>()).setVisible(true); // Asegúrate de pasar una lista vacía o existente
        }
    });
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BotonBonito botonBonito1;
    private BotonBonito botonBonito2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btningresar;
    private javax.swing.JCheckBox chkmostrarcontra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErrorContrasena;
    private javax.swing.JLabel lblErrorCorreo;
    private javax.swing.JLabel lblerrorcontraycorreo;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
